# Networking
listeners.tcp.default = 5672

# Memory
vm_memory_high_watermark.absolute = 600MB

# Disk
disk_free_limit.absolute = 1GB

# Heartbeat
heartbeat = 60

# Logging
log.console.level = info
log.file.level = info